version: "3.5"

services:
  punks:
    image: substrapunks
    ports:
      - 3001:3001
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - wsEndpoint=ws://node:9944
    networks: 
      - substrate_network

networks: 
  substrate_network:
    driver: bridge
    name: substrate_network
